### ISSUE TITLE
Update testing environment 

### ISSUE THREAD

**Issue by JacobTanenbaum** [eBay/go-ovn#107]
The testing environment is out of date, It would be better to bring in a more updated version of openvswitch and ovn to test against. 

As part of updating LRSRAdd() to support ecmp routes it I found that the version of ovs/ovn tested against does not support ecmp routes.

**Comment by noah8713** [comment]
yes ci can be improved to be switched to use ovs master and ovn 20.xx (latest)/master. Do you want to pick it up ? Else we can plan to pick it too cc @vtolstov @hzhou8

**Comment by JacobTanenbaum** [comment]
Yes, I should be able to pick this up
