### ISSUE TITLE
Add new loadbalancer fields

### ISSUE THREAD

**Issue by aojea** [eBay/go-ovn#112]
The OVN LoadBalancer added some new fields in the last releases
```
   Summary:
       name                          string
       vips                          map of string-string pairs
       protocol                      optional string, one of sctp, tcp, or udp
       health_check                  set of Load_Balancer_Health_Checks
       ip_port_mappings              map of string-string pairs
       selection_fields              set of strings, one of  eth_dst,  eth_src,  ip_dst,  ip_src,
                                     tp_dst, or tp_src
       Common Columns:
         external_ids                map of string-string pairs
```

but go-ovn only have

https://github.com/eBay/go-ovn/blob/da67e9744ec05bf817ef2de7128971f235b921c3/load_balancer.go#L25-L32

xref:
https://github.com/ovn-org/ovn/blob/master/ovn-nb.ovsschema#L188
http://manpages.ubuntu.com/manpages/hirsute/man5/ovn-nb.5.html#load_balancer%20table

**Comment by aojea** [comment]
I can work on this, just need some guidance on how to implement new fields keeping compatibility between ovn versions

**Comment by hzhou8** [comment]
@aojea Thanks for volunteering on this. For compatibility:
1) from OVSDB to go-ovn, if a column doesn't exist, just leave the go-ovn fields empty.
2) from go-ovn to OVSDB, if a column doesn't exist in schema, then don't add it to the transaction row. This may need a little more effort to check the DB schema.
