### ISSUE TITLE
introduce API force reconnect() for update SSL cert

### ISSUE THREAD

**Issue by winsopc** [eBay/go-ovn#127]
for SSL-based goovn client,  if the TLSconfig cert updated based on security, the client needs to disconnect the live connection and connect again use the updated TLSconfig.
@hzhou8  Any suggestions about how to support this?

the API can use internal function c.client.disconnect() and reconnect() I think.

**Comment by vtolstov** [comment]
tls config struct already have methods to get cert so you don't need to restart app for mTLS like stuff, but why you need to drop old connection forcable ?

**Comment by winsopc** [comment]
@vtolstov thanks for the quick reply.
Could you please share more info about how tlsconfig automatic load new key pairs?
I am referring the code goovn usage in ovn-kubernetes.
https://github.com/ovn-org/ovn-kubernetes/blob/master/go-controller/pkg/util/go_ovn.go
L70-L98.
cert, err := tls.LoadX509KeyPair(certFile, privKeyFile)
if the certFile, privKeyFile content changed,  my thinking is I need get new cert bytes and update to the *.tlsConfig.
but based my test goovn client will not use the cert unless the connection broken and reconnect callback happened.
please correct me if my understanding is wrong.

**Comment by vtolstov** [comment]
in this case this is not possible, you need to extend ovn-kubernetes to use https://golang.org/pkg/crypto/tls/#Config 
GetCertificate func(*ClientHelloInfo) (*Certificate, error) // Go 1.4
and 
GetClientCertificate func(*CertificateRequestInfo) (*Certificate, error) // Go 1.8

mostly you need to read google about mTLS in golang and dynamic certs

**Comment by winsopc** [comment]
Thanks for the info.
From the comments in the function:

// GetClientCertificate may be called multiple times for the same
--
  |   | // connection if renegotiation occurs or if TLS 1.3 is in use.
  |   | GetClientCertificate func(*CertificateRequestInfo) (*Certificate, error)

The function can be called when Server-side starts renegotiation when after the client in the connected state.
For goovn.Client,  the sever side is ovsdb-server which I support TLS1.2 1.1 1.0 from the man page.
http://www.openvswitch.org/support/dist-docs/ovsdb-server.1.html
My understanding is if ovsdb-sever process does not start renegotiation, then goovn.Client still use the old cert.
 Please correct me if my understanding if wrong.
Thanks for your help.

**Comment by vtolstov** [comment]
yesm may be, i don't know about tls version in ovn =(

**Comment by hzhou8** [comment]
I think an API like ForceReconnect() would be no different than calling Close() and NewClient() again. Maybe we should find a better to way to support dynamic cert rotation (maybe support it from ovsdb server side first).

**Comment by vtolstov** [comment]
@hzhou8 yeah, i think so

**Comment by winsopc** [comment]
@hzhou8 thanks for your comments. 
Yes, the application can use the current API to finish the task using your suggested method.
The reason I am thinking to introduce this API is making the current ovn-k8s code easy to support it.
From the application level,  if it detects cert/key pair change, then just update the tlsConfig cert file with goovn.Client.ForceReconnect().
