### ISSUE TITLE
move sources from goovn to top level dir

### ISSUE THREAD

**Issue by vtolstov** [eBay/go-ovn#13]
I'm prepare patches to error handling, does it possible after that move goovn sources to top-level dir? I don't now understand why created goovn dir from the beginning.

**Comment by hzhou8** [comment]
I don't remember the reason, but I guess it is ok to move to top level, if it helps shortening the module path. However, it creates backward compatibility problem, too, just like API change.

**Comment by vtolstov** [comment]
May be integrate go mod , and switch path?as if we branch v1 this is fine i
think.

вт, 12 мар. 2019 г., 20:14 Han Zhou <notifications@github.com>:

**Comment by hzhou8** [comment]
Sorry I am not familiar with go mod. I will read and get back to you.

**Comment by vtolstov** [comment]
This is next step i think for me, after that I'm plan to split ovnnbimp to logical pieces.
