### ISSUE TITLE
When reconnecting, deleted rows are not handled

### ISSUE THREAD

**Issue by fedepaol** [eBay/go-ovn#147]
We have the following scenario in ovnk.
Some records (in this case LSPs) are deleted from nbdb, and a few seconds after we see a disconnection:

```
2021-04-19T11:40:26.193749278Z 2021/04/19 11:40:26 rpc2: client protocol error: read tcp 172.21.8.55:52212->172.21.8.53:9642: read: connection reset by peer
2021-04-19T11:40:26.193812317Z 2021/04/19 11:40:26 ssl:172.21.8.53:9642,ssl:172.21.8.55:9642,ssl:172.21.8.59:9642 disconnected. Reconnecting ... 
2021-04-19T11:40:26.701238456Z 2021/04/19 11:40:26 ssl:172.21.8.53:9642,ssl:172.21.8.55:9642,ssl:172.21.8.59:9642 reconnected.
2021-04-19T11:40:28.754648075Z 2021/04/19 11:40:28 rpc2: client protocol error: read tcp 172.21.8.55:45308->172.21.8.53:9641: read: connection reset by peer
2021-04-19T11:40:28.754903588Z 2021/04/19 11:40:28 ssl:172.21.8.53:9641,ssl:172.21.8.55:9641,ssl:172.21.8.59:9641 disconnected. Reconnecting ... 
```

What I am seeing is that, after the reconnection, the cache still contains one of those records which was supposed to be deleted.
What I believe is happening is that when we reconnect, and we try to re-align the cache contents in
https://github.com/eBay/go-ovn/blob/7376ba97f8cd9ea85a3c1cdb114e9057f8c3c370/client.go#L306

`MonitorTables` only returns existing items (as opposed to when `populateCache` is called from `Update`, where we get also the uuid / empty struct pairs.

I tried to validate with logs doing the following:

With master running, I put a "updating" log here https://github.com/eBay/go-ovn/blob/7376ba97f8cd9ea85a3c1cdb114e9057f8c3c370/ovnimp.go#L246 , I created and deleted the pod and I see the empty struct coming:
```
Updating  0f6f40ea-b35a-4163-bd26-97af9d25a17f {map[_version:{5448a880-b9bf-4b74-b547-fb90e7e2e17c} addresses:{[]} dhcpv4_options:{[]} dhcpv6_options:{[]} dynamic_addresses:{[]} enabled:{[]} external_ids:{map[namespace:test pod:true]} ha_chassis_group:{[]} name:test_client options:{map[requested-chassis:ovn-worker]} parent_name:{[]} port_security:0a:58:0a:f4:02:05 10.244.2.5 tag:{[]} tag_request:{[]} type: up:false]}
Updating  0f6f40ea-b35a-4163-bd26-97af9d25a17f {map[]}
```

This is not happening when I start the master again, looking for the same uuid.
```
kubectl -n ovn-kubernetes logs ovnkube-master-6fbb9f798c-ggsdz -c ovnkube-master | grep 0f6f40ea-b35a-4163-bd26-97af9d25a17f
```
Returns empty.

@hzhou8 does it make sense? If so I can propose a fix.

**Comment by fedepaol** [comment]
cc @trozet

**Comment by dave-tucker** [comment]
@fedepaol this makes sense.

When disconnected you won't get events for a deletion and there is no mechanism to remove stale entries.
The simplest fix would be to (re)initialize the cache before the Monitor.

```
 c.cache = make(map[string]map[string]libovsdb.Row)
 initial, err := c.MonitorTables("") 
 ```
 
Or I guess you could get fancy and provide an `intial bool` to `populateCache` and have it delete stale entries.

Also looking at the code, this looks like another potential bug:
https://github.com/eBay/go-ovn/blob/7376ba97f8cd9ea85a3c1cdb114e9057f8c3c370/client.go#L312

The callback for update notifications is registered *after* the monitor is set up and cache is populated.
Any events that occur in that time will be discarded. This fix might be less straight forward because you the updates and initial population might be fighting for the same locks.

**Comment by abhat** [comment]
if the notifier is registered before calling `c.MonitorTables("")`, we would still get updates for events in flight?

**Comment by fedepaol** [comment]
> @fedepaol this makes sense.
> 
> When disconnected you won't get events for a deletion and there is no mechanism to remove stale entries.
> The simplest fix would be to (re)initialize the cache before the Monitor.
> 
> ```
>  c.cache = make(map[string]map[string]libovsdb.Row)
>  initial, err := c.MonitorTables("") 
> ```
> 

Oh, nice. I thought only to the below one, but this seems way more straightforward and less error prone.

> Or I guess you could get fancy and provide an `intial bool` to `populateCache` and have it delete stale entries.
> 
> Also looking at the code, this looks like another potential bug:
> 
> https://github.com/eBay/go-ovn/blob/7376ba97f8cd9ea85a3c1cdb114e9057f8c3c370/client.go#L312
> 
> The callback for update notifications is registered _after_ the monitor is set up and cache is populated.
> Any events that occur in that time will be discarded. This fix might be less straight forward because the updates and initial population might be fighting for the same locks.

I'll try to push a fix that locks the mutex while doing the initial load so it has precedence over the callbacks.

**Comment by fedepaol** [comment]
> if the notifier is registered before calling `c.MonitorTables("")`, we would still get updates for events in flight?

Not sure I get the question right, but If we register it before (and it's registered), there can't be missed events because we make sure that there are no holes between the initial dump (`MonitorTables`) and when we add the notifier.

**Comment by abhat** [comment]
Correct, I think Dave is concerned that the notifier is registered later
right now and there is a potential window between calling MonitorTables and
Register where if any event gets fired, it will be missed.

**Comment by dave-tucker** [comment]
> if the notifier is registered before calling c.MonitorTables(""), we would still get updates for events in flight?

i'm not sure what you mean by "in flight", but, if a transaction was executed before the monitor was called, it would be in the initial state, if after it would come as an update.

**Comment by hzhou8** [comment]
Fixed by https://github.com/eBay/go-ovn/pull/148

In the future if libovsdb implements ovsdb monitor3 method, we will be able to keep the cache and ask the server for updates start from our last synced point so that no update will be missed and at the same time avoid resyncing all rows from server.
