### ISSUE TITLE
forking libovsdb

### ISSUE THREAD

**Issue by vtolstov** [eBay/go-ovn#23]
what do you think about forking libovsdb to Ebay namespace, add needed patches and use it on go-ovn without vendoring dir patching?

**Comment by hzhou8** [comment]
Yes, this is the plan. We are working on the process.

**Comment by vtolstov** [comment]
any news?

**Comment by vtolstov** [comment]
needed for #30

**Comment by vtolstov** [comment]
i'm forking to github.com/unistack-org/libovsdb and import related pr from original repo (ssl, blocking mode, and some other). i can transfer repo to you, but as i understand i need confirmation from you to this stuff

**Comment by hzhou8** [comment]
Sorry for the delay since there was some internal process to go through. Now it is forked to https://github.com/eBay/libovsdb
