### ISSUE TITLE
broken update notifications

### ISSUE THREAD

**Issue by vtolstov** [eBay/go-ovn#26]
I don't understand when tests are broken, but i'm check commit d91fdd20089671059e0201f604f3de3449b52f55 and it already broken
```
=== RUN   TestACLs
--- FAIL: TestACLs (0.00s)
    ovnnbimp_test.go:77:
                Error Trace:    ovnnbimp_test.go:77
                Error:          Not equal:
                                expected: true
                                actual  : false
                Test:           TestACLs
                Messages:       test[added port]: []
    ovnnbimp_test.go:78:
                Error Trace:    ovnnbimp_test.go:78
                Error:          Not equal:
                                expected: true
                                actual  : false
                Test:           TestACLs
                Messages:       test[setted port address]
    ovnnbimp_test.go:79:
                Error Trace:    ovnnbimp_test.go:79
                Error:          Not equal:  
                                expected: true
                                actual  : false
                Test:           TestACLs
                Messages:       test[setted port port security]
    ovnnbimp_test.go:85:
                Error Trace:    ovnnbimp_test.go:85
                Error:          Not equal:  
                                expected: true
                                actual  : false
                Test:           TestACLs
                Messages:       test[added 2 ports]: []
panic: runtime error: index out of range [recovered]
        panic: runtime error: index out of range
```

**Comment by vtolstov** [comment]
i'm test this commit because it before my changes

**Comment by vtolstov** [comment]
i found root case of issue, update received something later , so test function check item before update received.
I think that if cache is missed, we need directly get data from ovn

**Comment by vtolstov** [comment]
or add some flag to wait sync...
@hzhou8 @softwarejl do you have some solution?

**Comment by hzhou8** [comment]
It is an known issue and already fixed by fixing rpc2 (which was merged upstream: https://github.com/cenkalti/rpc2/commit/09ab3e86ec385d21488d0315a98c51dd3b71a27f) and then fixing libovsdb to use the new parameter (which was not merged upstream). The libovsdb fix was updated directly in our vendor folder (which was bad way of managing, and we are working on forking it under ebay). The PR is breaking this probably because it overwrites the changes we made in vendor/libovsdb.

**Comment by vtolstov** [comment]
do you know latest working commit?

**Comment by vtolstov** [comment]
p.s. i'm doing major rewrite internals of this package and may be after next hours can push fixed pr.
most things be more easy to write and understand via some helper like odbi.insertRowOp(table, row) and so

**Comment by vtolstov** [comment]
yes, i found. this is ssl stuff breaks. after rework missed piece c.SetBlocking(true), i'm add it to own branch.
