### ISSUE TITLE
set ipv6 slaac ra and dhcp v4

### ISSUE THREAD

**Issue by vtolstov** [eBay/go-ovn#3]
Hi. I'm try to use this package to provide network for my libvirt vm. How can i add dhcp info to specific port?
Also - do you have roadmap or some plans to enhance this package?

**Comment by vtolstov** [comment]
Also can you share via issues task needed to be done for L3 support.

**Comment by hzhou8** [comment]
Current APIs supports limited interfaces only. They should be either added on-demand, or change the implementation to be able to handle flexible parameters. PRs are welcome for both.
