### ISSUE TITLE
Meter and Meter bands method design problem.

### ISSUE THREAD

**Issue by JackyCZJ** [eBay/go-ovn#60]
I try to write meter and meter bands , now the problem is ``ovn-nbctl`` can only set one bands of each meter . and i see doc of ``ovn-nbctl`` said other ctl can set mutpli bands in one meter . So I wonder if we should follow ``ovn-nbctl`` or write own method to set meter and meter bands ?

you can check this patch , if anything ok ,  I will send a pr.
https://github.com/JackyCZJ/go-ovn/commit/76852e984d76423a7e628a5cf94ade1236013329

**Comment by vtolstov** [comment]
if that possible via api of ovn i think that we need to support this. ovn-nbctl is like example client for us,i think

**Comment by JackyCZJ** [comment]
#61
