### ISSUE TITLE
Tag version and ACLList miss meter and severity filed.

### ISSUE THREAD

**Issue by JackyCZJ** [eBay/go-ovn#62]
Currently master branch may dependent by orther project , I think it should tag like v1.0.0 for better go mod support? 

acl list can't show meter and severity .
https://github.com/eBay/go-ovn/blob/ca0da4d10c5264e6bb8083566be39f5bc7bd7181/acl.go#L24-L31

it miss meter filed
```
_uuid               : f8a9eb74-2a0c-48ad-b858-fb922e41fcd3
action              : drop
direction           : to-lport
external_ids        : {}
log                 : true
match               : "outport == \"96d44061-1823-428b-a7ce-f473d10eb3d0\" && ip && ip.dst == 10.97.183.61"
meter               : "meterTest1"
name                : []
priority            : 1001
severity            : []
```

**Comment by hzhou8** [comment]
@JackyCZJ Thanks for reporting this issue. It seems you are reporting 2 issues here?

1. You want to tag a version.

2. ACLList misses the meter and severity fields.

Do you mean you want a tag *before* the new fields are added to ACLList?

**Comment by JackyCZJ** [comment]
I think it is better that fix some problem before tag a version . maybe i should take two issue XD

**Comment by hzhou8** [comment]
I see. Sure, we can tag it as soon as the issues are fixed. Would like to send a patch for the missing meter fields?

**Comment by JackyCZJ** [comment]
I can send it , and this patch have two change ,
 1. add meter and meter band support.
 2. fix miss field.
should i send two pr or just mix at one?

and there have a pr name test , it seems a big change to this project , i think you can take a look to this pr #59

**Comment by hzhou8** [comment]
It is always good to have separate PRs for different problems. It is ok to have a single PR for related problems, if one fix depends on another one, but each problem should have a separate commit. In this case, you may send one PR with 2 commits. (or 2 PRs are ok if there is no dependency between them)

**Comment by hzhou8** [comment]
Yes, I am looking at #59 but it seems not ready and I also need more time :)

**Comment by JackyCZJ** [comment]
thank! i will take my time for this patch
