### ISSUE TITLE
change interface to not fatal or panic

### ISSUE THREAD

**Issue by vtolstov** [eBay/go-ovn#8]
What do you think about changing interface to return error and not doing fatal/os.Exit and panic?
I can provide pr to change interface definition and after that add ability to get/set dhcp options and other stuff

**Comment by softwarejl** [comment]
It's a good idea, please do not hesitate to submit your patches.

**Comment by vtolstov** [comment]
can i change strconv.Itoa(rand.Int() to google uuid.NewRandom() ?
i think that this is more suitable for such things

**Comment by vtolstov** [comment]
pr is created
